"""Update StockRequest model

Revision ID: 79636f3b01f3
Revises: 
Create Date: 2025-03-01 23:31:00.591499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79636f3b01f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ration_shop')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ration_shop_id')

    with op.batch_alter_table('stock_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stock_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_requested', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_processed', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'warehouse', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(None, 'farmer', ['farmer_id'], ['id'])
        batch_op.drop_column('to_id')
        batch_op.drop_column('stock_id')
        batch_op.drop_column('from_id')
        batch_op.drop_column('ration_shop_id')
        batch_op.drop_column('request_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('ration_shop_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('from_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('stock_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('to_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ration_shop', ['ration_shop_id'], ['id'])
        batch_op.create_foreign_key(None, 'stock', ['stock_id'], ['id'])
        batch_op.drop_column('date_processed')
        batch_op.drop_column('date_requested')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('notes')
        batch_op.drop_column('stock_type')
        batch_op.drop_column('warehouse_id')
        batch_op.drop_column('farmer_id')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ration_shop_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'ration_shop', ['ration_shop_id'], ['id'])

    op.create_table('ration_shop',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('manager_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('shop_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id')
    )
    # ### end Alembic commands ###
